<?php

declare(strict_types=1);

namespace Iriven\PhpFormGenerator\Application\Cli;

/**
 * @api
 */
final class MakeFormCommand implements CliCommandInterface
{
    public function name(): string
    {
        return 'make:form';
    }

    /**
     * @param array<int, string> $args
     */
    public function run(array $args = []): string
    {
        $name = $args[0] ?? 'GeneratedFormType';

        return <<<TXT
<?php

declare(strict_types=1);

final class {$name}
{
    public function buildForm(): void
    {
        // TODO: scaffold generated by make:form
    }
}
TXT;
    }
}
