checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - "vendor/*"
    - "docs/*"

build:
  image: default-jammy

  environment:
    variables:
      XDEBUG_MODE: coverage

  nodes:
    analysis:
      environment:
        php:
          version: 8.2

      dependencies:
        override:
          - composer install --no-interaction --prefer-dist 

      tests:
        override:
          - command: vendor/bin/phpunit --colors=never --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: php-clover
          - php-scrutinizer-run
