imports:
  - php

filter:
  excluded_paths:
    - "vendor/*"
    - "tests/*"
    - "docs/*"

checks:
  php:
    code_rating: true
    duplication: true

build:
  image: default-jammy

  nodes:
    analysis:
      environment:
        php: 8.2
      dependencies:
        override:
          - composer install --no-interaction --prefer-dist
      tests:
        override:
          - vendor/bin/phpunit --colors=never
          - php-scrutinizer-run