build:
  nodes:
    analysis:
      project_setup:
        override:
          - composer install --no-interaction
      tests:
        override:
          - command: vendor/bin/phpunit
            coverage:
              file: coverage.xml
              format: clover

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*
    - vendor/*
